services:
  postgres:
    image: bitnami/postgresql
    container_name: postgres_viagens_db
    volumes:
      - ./data:/bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gui
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: viagensdbapi
